适配 QQ 频道
Quan666/ELF_RSS pull request #250
Opened 2022-02-17 11:01 UTC by mobyw

### 🐛 Bug 修复

- 修复无法以缺省链接方式添加已经存在的订阅的问题。#249

### 💫 杂项

- 更新版本号为 `v2.5.1`。
- 移除版本过旧的 `install.sh`，`gocqhttp` 的安装与配置可考虑使用 `nonebot-plugin-gocqhttp` 插件实现。
- 移除不必要的 `__init__.py` 文件。
- 移除 `bot.py` 中的插件导入部分，使用 `require` 方式可自动导入。
- 移除未适配当前版本 `nonebot2` 的依赖 `nonebot-test`。
- 修改 `nonebot2` 及 `adapter` 依赖为范围表示，以获取最新版本。
- 添加频道适配插件 `nonebot-plugin-guild-patch`。
- 添加 `patch.py` 文件，实现频道中的 `to_me()` 规则。
- 由于频道中 `Sender` 的 `role` 表示方法不同，暂时采用手工添加账号的方式。
    - 添加 `GUILD_SUPERUSERS` 配置项。
    - 添加 `permission.py` 文件，实现 `GUILD_SUPERUSERS` 权限。
- 补充 `rss_class` 中的 `typing`。
- 规范 `import` 内容，删除未使用的 `import`。

### 🍻 功能更新

- 添加子频道订阅功能。 #245
    - 可从旧版直接升级，保留订阅数据。
    - 子频道订阅需要使用 `gocqhttp v1.0.0-beta8-fix2` 及以上版本。
    - 由于目前频道消息上报，需要在 `.env` 中配置 `GUILD_SUPERUSERS` 填写管理员频道号。
    - 新加入频道的 QQ 可能需要重启 `gocqhttp` 才能正常接收频道消息。

2022-02-17 13:12 UTC, NekoAria requested changes
这些文件需要用 Black 格式化后才能通过合并前的检查：
```
src/plugins/ELF_RSS2/RSS/routes/Parsing/send_message.py
src/plugins/ELF_RSS2/add_cookies.py
src/plugins/ELF_RSS2/bot_info.py
src/plugins/ELF_RSS2/config.py
src/plugins/ELF_RSS2/permission.py
src/plugins/ELF_RSS2/show_all.py
src/plugins/ELF_RSS2/change_dy.py
src/plugins/ELF_RSS2/upload_group_file.py
```

2022-02-17 14:16 UTC, mobyw commented
已提交代码格式化。

2022-02-17 16:50 UTC, mobyw reviewed
review

2022-02-18 01:20 UTC, Quan666 approved these changes

2022-02-18 11:53 UTC, NekoAria approved these changes

2022-02-18 11:53 UTC, merged